<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class TeamsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('teams')->insert([
            [
                'team_id' => '1' ,
                'user_id' => '1' ,
                'name' => 'テストチーム_1',
                'name_kana' => 'テストチーム_1' ,
                'representative' => 'テストさん' ,
                'member_count' => '5人以下',
                'area' => '新宿区',
                'age_group' => '20代' ,
                'category' => '競技系チーム',
                'mood_enjoy' => '1' ,
                'mood_sanity' => '5' ,
                'create_year' => '2000年' ,
                'create_month' => '5月' ,
                'tag' => '男性のみ' ,
                'introduction' => 'よろしくお願いします。' ,
                'image' => 'test.test' ,
                'url_path' => 'test url' ,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'team_id' => '2' ,
                'user_id' => '2' ,
                'name' => 'テストチーム_2',
                'name_kana' => 'テストチーム_2' ,
                'representative' => 'テストさん' ,
                'member_count' => '6人',
                'area' => '中央区',
                'age_group' => '30代' ,
                'category' => '競技系チーム',
                'mood_enjoy' => '1' ,
                'mood_sanity' => '5' ,
                'create_year' => '2000年' ,
                'create_month' => '5月' ,
                'tag' => '男性のみ' ,
                'introduction' => 'よろしくお願いします。' ,
                'image' => 'test.test' ,
                'url_path' => 'test url' ,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'team_id' => '3' ,
                'user_id' => '3' ,
                'name' => 'テストチーム_3',
                'name_kana' => 'テストチーム_3' ,
                'representative' => 'テストさん' ,
                'member_count' => '5人以下',
                'area' => '新宿区',
                'age_group' => '20代' ,
                'category' => '競技系チーム',
                'mood_enjoy' => '1' ,
                'mood_sanity' => '5' ,
                'create_year' => '2000年' ,
                'create_month' => '4月' ,
                'tag' => '男性のみ' ,
                'introduction' => 'よろしくお願いします。' ,
                'image' => 'test.test_1' ,
                'url_path' => 'test url_1' ,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'team_id' => '4' ,
                'user_id' => '4' ,
                'name' => 'テストチーム_4',
                'name_kana' => 'テストチーム_4' ,
                'representative' => 'テストさん' ,
                'member_count' => '5',
                'area' => '足立区',
                'age_group' => '20代' ,
                'category' => '競技系チーム',
                'mood_enjoy' => '1' ,
                'mood_sanity' => '5' ,
                'create_year' => '2010年' ,
                'create_month' => '7月' ,
                'tag' => '男性のみ' ,
                'introduction' => 'よろしくお願いします。' ,
                'image' => 'test.test' ,
                'url_path' => 'test url' ,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'team_id' => '5' ,
                'user_id' => '5' ,
                'name' => 'テストチーム_5',
                'name_kana' => 'テストチーム_5' ,
                'representative' => 'テストさん' ,
                'member_count' => '5',
                'area' => '新宿区',
                'age_group' => '20代' ,
                'category' => '競技系チーム',
                'mood_enjoy' => '1' ,
                'mood_sanity' => '5' ,
                'create_year' => '2000年' ,
                'create_month' => '5月' ,
                'tag' => '男性のみ' ,
                'introduction' => 'よろしくお願いします。' ,
                'image' => 'test.test' ,
                'url_path' => 'test url' ,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'team_id' => '6' ,
                'user_id' => '6' ,
                'name' => 'テストチーム_6',
                'name_kana' => 'テストチーム_6' ,
                'representative' => 'テストさん' ,
                'member_count' => '5',
                'area' => '新宿区',
                'age_group' => '20代' ,
                'category' => '競技系チーム',
                'mood_enjoy' => '1' ,
                'mood_sanity' => '5' ,
                'create_year' => '2000年' ,
                'create_month' => '5月' ,
                'tag' => '男性のみ' ,
                'introduction' => 'よろしくお願いします。' ,
                'image' => 'test.test' ,
                'url_path' => 'test url' ,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'team_id' => '7' ,
                'user_id' => '7' ,
                'name' => 'テストチーム_7',
                'name_kana' => 'テストチーム_7' ,
                'representative' => 'テストさん' ,
                'member_count' => '5',
                'area' => '新宿区',
                'age_group' => '20代' ,
                'category' => '競技系チーム',
                'mood_enjoy' => '1' ,
                'mood_sanity' => '5' ,
                'create_year' => '2000年' ,
                'create_month' => '5月' ,
                'tag' => '男性のみ' ,
                'introduction' => 'よろしくお願いします。' ,
                'image' => 'test.test' ,
                'url_path' => 'test url' ,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'team_id' => '8' ,
                'user_id' => '8' ,
                'name' => 'テストチーム_7',
                'name_kana' => 'テストチーム_7' ,
                'representative' => 'テストさん' ,
                'member_count' => '5',
                'area' => '新宿区',
                'age_group' => '20代' ,
                'category' => '競技系チーム',
                'mood_enjoy' => '1' ,
                'mood_sanity' => '5' ,
                'create_year' => '2000年' ,
                'create_month' => '5月' ,
                'tag' => '男性のみ' ,
                'introduction' => 'よろしくお願いします。' ,
                'image' => 'test.test' ,
                'url_path' => 'test url' ,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
